feat: added create-trip form control
Muh-Hasan/journeo pull request #14
Opened 2024-08-27 20:53 UTC by Muh-Aqib-Shah

**Submit** button now works allowing logged In users to submit there trips from the create trips form, allowing the trip to be stored in db. Users are notified about form submission through a toast. Only logged In users can submit the form otherwise a "Not Logged In" toast is shown, in case of a error a Internal server error is sent by the api wich is handled and a erronous toast is shown to user.

2024-08-28 18:50 UTC, Muh-Hasan requested changes
- Add `create-trip` to the middleware file to prevent users from being redirected if they are not logged in.

- On submission, the previous button remains active, allowing the user to toggle between the forms; it should be disabled.

- Attach a route between '/trips' and '/create-trip' to the 'new trip' button on the '/trips' page.

- Use this toast: https://ui.shadcn.com/docs/components/sonner

2024-08-28 18:50 UTC, Muh-Hasan commented on .env.example
It was an example used to help others set up a project; please re-add the file.

2024-08-28 18:50 UTC, Muh-Hasan commented on src/components/create-trip/hotel-details.tsx
> +            <svg
Use the loader icon from the icon library and add the 'animate-spin' class to it.

2024-08-30 18:15 UTC, Muh-Aqib-Shah commented
implemented the changes as you requested!

2024-08-31 15:16 UTC, Muh-Hasan approved these changes
Looks good!

2024-08-31 15:16 UTC, merged